#!/bin/bash
#

# Change to experiments/inductive_proofs directory
cd experiments/inductive_proofs

PROVER1=$1
PROVER2=$2

for f in *.thy; do
    echo "Processing $f file..";

    # Changing oops to by $PROVER
    sed -i '.bak' "s/by $PROVER1/by $PROVER2/g" $f
done

