#!/bin/bash
#

FULLFILE=$1

LOGIC=$2

DIR=$(dirname "$FULLFILE")

FILE=`echo ${FULLFILE%.*}`
THEORY=`echo ${FILE##*/}`

echo $FILE
echo $THEORY
echo $DIR

# Change to directory containing theory file
cd $DIR

# Calling the isabelle process
 timeout -t 120 isabelle_process -e "use_thy \"$THEORY\";" -q -r $LOGIC
